---
title: details of implmenting the table saw
---

- todo:
  - level the bench 
    - use shims to level table top surface, and then cut all four legs
      - make sure the floor is also level
      - good idea https://www.youtube.com/watch?v=vq94qo7WbEw
  - test the apron, build a clamp aid tmp fence
  - use the fence and router to cut 12.80 deep 30 wide slots
    - how far from the blade?
      - 5inch or so, I will make it 12cm
  - change strechers
    - https://youtu.be/UlElSbqD3jc?t=79
      - I think I will not rip the 4x14
- kickbacks
  - https://youtu.be/6zLdB3zil_E?t=51
    - two lessons:
      - push stick should be tall
      - always have the piece between black and fence under your push stick
  - https://youtu.be/eUx8oTIALmg?t=385
    - lesson: control the work piece until it leaves the blade conpletely. If this guy used a push stick to give a downward force to the wood, these would not have happened.
  - to aviod kickback, mesuare the angel of the blade and table surface to make sure it is 90degree, and make sure the fence and the blade is in perfect parallel
    - https://www.youtube.com/watch?v=vV691tXe4RQ
    - https://www.youtube.com/watch?v=68xLIougMv0
  - riving knife
    - https://www.youtube.com/watch?v=haYWxqjss_g
    - even pros dont always use it https://youtu.be/S9PTFizoA64?t=55
    - my cicular saw can not install riving knife, but as long as I don't use rip fence to do cross-cut, I will be OK https://youtu.be/tKtE0sTFi8g?t=634
  - kickbacks can be horrible https://www.youtube.com/watch?v=eUx8oTIALmg
    - that is why your riving knife is necessary https://youtu.be/eUx8oTIALmg?t=541
    - and your push stick can also give you extra protect, even the kickback happens
    - your body out of the kickback path, like this https://youtu.be/un2YUPlgh8c?t=214
  - don't use table saw to cut small things
    - things will fly, and your hands may get too close to the saw
    - never cut narrow things like this piece https://youtu.be/eUx8oTIALmg?t=1469
      - https://youtu.be/tKtE0sTFi8g?t=630
      - use miter saw  
      - or use you miter guage https://youtu.be/JOhZxvgkWNM?t=346
        - people call this case 'cross cut', and 'don't use your fence when cross cuting'
  - don't fasten the nut too much https://youtu.be/JOhZxvgkWNM?t=336
  - place the push stick close to the blade, not the fence
    - https://youtu.be/eUx8oTIALmg?t=1635
      - in the video's case, if your wood is not very small, and you have riving knife in place, you should not have this problem
    - the idea is aviod rotation of the wood by all means
    - this is actully a very important tip, knowing this free u to buy this https://youtu.be/hRygWpXXYJ4?t=86
  - how to do a cut
    - https://youtu.be/tKtE0sTFi8g?t=727
    - eyes on the fence, not the blade
    - one hand push forward, the other push wood downward to the table and against the fence
    - when the cut is done, push the piece(especially the work piece, because your cut-off piece is always on the left side of the blade) off the blade
  - a insert plate is necessary
    - https://youtu.be/tKtE0sTFi8g?t=284
  - don't use miter guage and rip fence together https://youtu.be/tKtE0sTFi8g?t=368
  - push the wood to the fence, give it a trend to leave the blade https://youtu.be/5ADbrYJtDP8?t=208
  - don't leave the smaller part between the blade and fence https://youtu.be/5ADbrYJtDP8?t=234
    - two reasons: 1. small things fly esaily, 2. kickbacks do not happen on the oppsite side of the fence
  - what is a kickback https://youtu.be/5ADbrYJtDP8?t=184

- install circular
  - blade position
    - the trick is to setup a Coordinate System before you do everything
      - you don't need all corners perfectly 90degree
      - all you need is to trust one corner, then use that as orgin
      - now all I need to make sure the blade is in perfect parrellel with y axis
    - center of the surface
      - https://www.youtube.com/watch?v=l_vlA0crb4c&t=269s
      - https://www.youtube.com/watch?v=dF5RjNDCKlU
  - https://www.youtube.com/watch?v=B1cvo-VbYqU
    - make a box to support the saw
    - how to cut a hole for 45degree 
    - how to drill holes on the saw panel
  - change angels
    - really advanced version of wood version https://www.ixigua.com/6567978658206581261
  - add cover board to avoid cut-offs from dropping in to the saw
    - https://youtu.be/z2RDzpg03aU?t=612


- bench 
  - general look
    - https://www.youtube.com/watch?v=jAEykXezb6I
  - frame
    - https://www.youtube.com/watch?v=mHIe9VSikbA
      - all the aprons and legs should be kept perfectly 90degree against table top
        - this is the one single point to focus on when you assemble the table
        - foucing on two many metrics, makes the work very hard to finish
          - some numbers are not that useful, since the pieces are not always perfectly cut
        - before drilling for screws, do use clamps
      - follow the video, use 40x70 to get a perfect 800x600 squere
      - then at this point https://youtu.be/mHIe9VSikbA?t=110
        - I don't have that long screws, so I will use some wood triangles to fasten the table top, of course, not screws shown on the table up
      - then at https://youtu.be/mHIe9VSikbA?t=128
        - same problem, no long enough screws
        - I will use plywood as sidestrechers, as https://youtu.be/vqFIDi0QqhM?t=466
  - height
    - I have 83cm legs
    - 830+17=847cm, is it a good height?
    - google told me the best height for me is around 81cm, which is from my thumb knuckle to the floor
  - width
    - 2~3feet(60~90cm) recommended, I will use 80cm
      - make it wide, have places for tracks and fence
  - length
    - 60cm, make it short, too long with make work harder

- NOTE:
  - when I build a new bench for the saw, try to make sure when the saw is back to 0 degree, the blade is 90degree from the table surface
  - make sure the edges of the surface is either 90 or 0 degree to the blade
  - make sure the blade angel is easy to change, use hinges?
    - table top screw https://youtu.be/dF5RjNDCKlU?t=478

- rip fence
  - fun fact
    - even my fence right now was not parallel with the blad at all, but the cut gets me perfect result(<1mm error in width for a 30cm long piece), I guess, it just mades the kerf bigger
  - bugfix
    - use ply wood for the track
    - make the slot deeper, even if means I need to change the runner
  - why I don't want to fasten two ends 
    - shortcoming: have something on both ends, make it impossible to put another table close to the saw table
    - https://www.youtube.com/watch?v=cOMWPyCX6QY
    - https://www.youtube.com/watch?v=W0CuwAkvvMU
  - why you need a box rather than a piece of solid wood?
    - your fence needs to be tall and sturdy, but not heavy, which will make it hard to move around.
  - BEST SOLUTION:
    - https://www.youtube.com/watch?v=KqKZh90cvg8
      - improvements:
        - destroying and get the moving part of my little clamp
        -  seal the clamp embedded with wood shim and glue
        - because my slot is shallow, so the runner has to be kind of thin, and easily broke off the fence, so embedded 10mm into the fence will make a difference
    - further improvements
      - if you want silk smooth sliding, try this bearing version track https://youtu.be/68xLIougMv0?t=497
        - T track version https://www.youtube.com/watch?v=2bpfvXTmXKA
          - https://youtu.be/y0R5rO1jJqM?t=466
          - the problem of this solution is when the fence is not locked, it would be play on the oppisite side 
      - add ruler https://www.youtube.com/watch?v=FIhMBYwm9E8

- t track/MITER-SLOT
  - NOTE:
    - cut the track to be the size of "木工 T 滑条“ I bookmarked on PDD
    - try wood version first, if not working, then buy the aluminum track
    - use plywood to build runners https://youtu.be/0gvx-_YipOs?t=132
  - sled
    - Best solution: https://youtu.be/pZfyoh5SZ6I?t=267
    - add a clamp for repetitive cuts https://youtu.be/tf2gaSmNqcg?t=400
- A width direction EXTENSION TABLE
  - https://youtu.be/0ICV6vasPIk?t=334
- switch
  - https://youtu.be/z2RDzpg03aU?t=689
  - knee stoppable button
- 45 degree
  - a simple way https://www.youtube.com/watch?v=7VHJuUyx6aA
    - if you don't use 45 degree very often
- push stick
  - best: https://youtu.be/6zLdB3zil_E?t=14
  - I find long push stick does not give me enough control, the wood will very likely lean off the fense with a stick like this https://youtu.be/tKtE0sTFi8g?t=746
  - I want a tall push stick, whick also my to give force to 3 directions at the same time: to the fence, downward, forward.
- mistakes
  - pressing against the blade https://youtu.be/JOhZxvgkWNM?t=166
    - this also shows a push block is better than a push stick
- cut thin strips safe&easy
  - https://www.youtube.com/watch?v=pZfyoh5SZ6I
- blade life mechanism
  - https://www.youtube.com/watch?v=Lagcm4Y9j6c&list=PL7c2ysQbjIBZedVGH9EM2dmj2CNdp67o6