" why I use *,* to do mapping?
" inspired by Derek, the reasons:
" 1. <LEADER> is too long to type
" 2. *,* is easier to reach than *\*
" 3. in practice you nerver type in *,v*, but *, v*
" Derek also do a nomap for *,*
"   nnomap <c-e> ,
" I do not do it, since I do not use *,* as a command a lot
"""""edit vimrc
map ,v :vnew ~/.vimrc<CR>
"set quick escape from insert mode, and now I can go without arrow keys and
" use j and k to move around in insert mode
imap JJ <esc>
imap jj <esc>
imap kk <esc>
imap KK <esc>
"input abrevation 
iab frm from 
" prefer to use the wildmode same as bash
set wim=list


" perfect solution to do tabing

set expandtab
set shiftwidth=4
set tabstop=4

" have nice $ sign when you use `cw`
set cpoptions+=$

" Do not know how to use autocmd yet, so the following line not working
"   autocmd FileType text setlocal textwidth=78
set textwidth=78

""""""""""DICT""""""""""""
"use i_CTRL_X_K for dict
set dictionary+=~/.vim/dict/simple
" the ic for dict somethings works something sucks
set ic 
set dictionary-=/usr/share/dict/words dictionary+=/usr/share/dict/words

set wildmenu
